version: '3'
services:
  flask:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:80"
    environment:
      PYTHONIOENCODING: utf-8
    tty: true
    container_name: flask_app
    